# Generated by Django 3.2.10 on 2023-06-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20230604_0821'),
    ]

    operations = [
    ]
