# Generated by Django 3.2.10 on 2023-06-07 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20230607_0759'),
    ]

    operations = [
    ]
