# Generated by Django 3.2.10 on 2023-06-07 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20230607_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='random_id',
            field=models.PositiveIntegerField(default=695, unique=True),
        ),
    ]
