# Generated by Django 3.2.10 on 2023-06-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20230607_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='random_id',
            field=models.PositiveIntegerField(default=724, unique=True),
        ),
    ]
