# Generated by Django 3.2.10 on 2023-06-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_random_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='random_id',
            field=models.PositiveIntegerField(default=113, unique=True),
        ),
    ]
