# Generated by Django 3.2.10 on 2023-07-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_alter_video_random_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='random_id',
            field=models.PositiveIntegerField(default=287, unique=True),
        ),
    ]
