# Generated by Django 3.2.10 on 2023-05-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
