# Generated by Django 3.2.10 on 2023-06-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230603_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='random_id',
            field=models.PositiveIntegerField(default=2247, unique=True),
        ),
    ]
