# Generated by Django 3.2.10 on 2023-06-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230603_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='random_id',
            field=models.PositiveIntegerField(default=4384, unique=True),
        ),
    ]
