# Generated by Django 3.2.10 on 2023-06-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_tag_random_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='random_id',
            field=models.PositiveIntegerField(default=4258, unique=True),
        ),
    ]
