# Generated by Django 3.2.10 on 2023-07-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
